version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kokoro
      - zonos

  kokoro:
    build:
      context: ./kokoro
      target: final-cpu
      args:
        BUILD_TYPE: cpu # ⬅️ 동일하게 CPU로 지정
    container_name: kokoro
    ports:
      - "8081:8080"

  zonos:
    build:
      context: ./zonos
    container_name: zonos
    ports:
      - "8082:8080"
#docker-compose up -d
