name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 트리거됨
  pull_request:
    branches:
      - main # pull request가 main에 생성되었을 때 트리거됨

jobs:
  build:
    runs-on: ubuntu-latest # 빌드가 실행될 환경

    steps:
      # 1. Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Log in to Docker Hub (선택 사항, Docker Hub에 푸시하려면 필요)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build Docker image (CPU 버전으로 빌드)
      - name: Build Docker image (CPU)
        run: |
          docker build --target final-cpu -t your-dockerhub-username/tts-server:latest .

      # 5. Run Docker container (if needed)
      - name: Run Docker container
        run: |
          docker run -d -p 8080:8080 your-dockerhub-username/tts-server:latest

      # 6. Push Docker image to Docker Hub (선택 사항)
      - name: Push Docker image to Docker Hub
        run: |
          docker push your-dockerhub-username/tts-server:latest
        if: github.ref == 'refs/heads/main' # Only push if the branch is main
